version: '3.4'

services:
  netbox:
    image: netboxcommunity/netbox:v3.5
    container_name: netbox
    environment:
      - DB_HOST=postgres
      - DB_NAME=netbox
      - DB_USER=netbox
      - DB_PASSWORD=dbpass
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    volumes:
      - ./netbox:/opt/netbox/netbox/media
    ports:
      - "8000:8080"
    depends_on:
      - postgres
      - redis
	  
  postgres:
    image: postgres:13
    container_name: postgres
    environment:
      - POSTGRES_DB=netbox
      - POSTGRES_USER=netbox
      - POSTGRES_PASSWORD=dbpass
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:6.2
    container_name: redis
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data:
