- name: Setup NetBox Docker
  hosts: all  # Adjust if you want to run on a remote server
  become: yes
  tasks:

    - name: Install Docker
      ansible.builtin.package:
        name: docker.io
        state: present

    - name: Install required dependencies for Docker Compose
      ansible.builtin.package:
        name:
          - curl
          - python3-pip
          - libffi-dev
          - gcc
          - g++ 
          - docker.io
          - docker-compose
        state: present

    - name: Create projects directory
      ansible.builtin.file:
        path: "~/projects"
        state: directory
        mode: '0755'

    - name: Clone NetBox Docker repository
      ansible.builtin.git:
        repo: "https://github.com/netbox-community/netbox-docker.git"
        dest: "~/projects/netbox-docker"
        version: "release"
        force: yes

    - name: Add docker-compose override to expose port 8000
      ansible.builtin.copy:
        dest: "~/projects/netbox-docker/docker-compose.override.yml"
        content: |
          version: '3.4'
          services:
            netbox:
              ports:
                - "8000:8080"
        mode: '0644'

- name: Test change config
  shell:
    cmd: |
      sed -i '1i version: '\''3.4'\''' docker-compose.yml

- name: Test 2 netbox-worker
  shell:
    cmd: |
      sed -i '/netbox-worker:/,/condition: service_healthy/{s/depends_on:.*/depends_on:\n      - netbox/; /condition: service_healthy/d}' docker-compose.yml

- name: Test 2 netbox-housekeeping
  shell:
    cmd: |
      sed -i '/netbox-housekeeping:/,/condition: service_healthy/{s/depends_on:.*/depends_on:\n      - netbox/; /condition: service_healthy/d}' docker-compose.yml


    - name: Pull the latest NetBox Docker images
      shell:
        cmd: "docker-compose pull"
        chdir: "~/projects/netbox-docker"
      register: pull_output

    - name: Bring up the NetBox Docker containers in detached mode
      shell:
        cmd: "docker-compose up -d"
        chdir: "~/projects/netbox-docker"
      register: up_output

    - name: Create NetBox superuser
      shell:
        cmd: "docker-compose exec netbox /opt/netbox/netbox/manage.py createsuperuser"
        chdir: "~/projects/netbox-docker"
      async: 600
      poll: 0
      ignore_errors: true
