- name: Setup NetBox Docker
  hosts: localhost  # Adjust if you want to run on a remote server
  become: yes
  tasks:

    - name: Create projects directory
      ansible.builtin.file:
        path: "~/projects"
        state: directory
        mode: '0755'

    - name: Clone NetBox Docker repository
      ansible.builtin.git:
        repo: "https://github.com/netbox-community/netbox-docker.git"
        dest: "~/projects/netbox-docker"
        version: "release"
        force: yes

    - name: Add docker-compose override to expose port 8000
      ansible.builtin.copy:
        dest: "~/projects/netbox-docker/docker-compose.override.yml"
        content: |
          version: '3.4'
          services:
            netbox:
              ports:
                - "8000:8080"
        mode: '0644'

    - name: Pull the latest NetBox Docker images
      ansible.builtin.command:
        argv:
          - docker-compose
          - pull
        chdir: "~/projects/netbox-docker"
      register: pull_output

    - name: Bring up the NetBox Docker containers in detached mode
      ansible.builtin.command:
        argv:
          - docker-compose
          - up
          - -d
        chdir: "~/projects/netbox-docker"
      register: up_output

    - name: Create NetBox superuser
      ansible.builtin.command:
        argv:
          - docker-compose
          - exec
          - netbox
          - /opt/netbox/netbox/manage.py
          - createsuperuser
        chdir: "~/projects/netbox-docker"
      async: 600
      poll: 0
      ignore_errors: true
