- name: Setup NetBox Docker
  hosts: all  # Adjust if you want to run on a remote server
  become: yes
  tasks:

    - name: Install Docker
      ansible.builtin.package:
        name: docker.io
        state: present

    - name: Install required dependencies for Docker Compose
      ansible.builtin.package:
        name:
          - curl
          - python3-pip
          - libffi-dev
          - gcc
          - g++ 
        state: present

    - name: Download Docker Compose binary
      ansible.builtin.get_url:
        url: "https://github.com/docker/compose/releases/download/$(curl -s https://api.github.com/repos/docker/compose/releases/latest | jq -r .tag_name)/docker-compose-$(uname -s)-$(uname -m)"
        dest: /usr/local/bin/docker-compose
        mode: '0755'
      become: yes
      when: ansible_os_family == "Debian"  # Ensure this is the right condition for your system, you can remove 'when' if unsure.

    - name: Create projects directory
      ansible.builtin.file:
        path: "~/projects"
        state: directory
        mode: '0755'

    - name: Clone NetBox Docker repository
      ansible.builtin.git:
        repo: "https://github.com/netbox-community/netbox-docker.git"
        dest: "~/projects/netbox-docker"
        version: "release"
        force: yes

    - name: Add docker-compose override to expose port 8000
      ansible.builtin.copy:
        dest: "~/projects/netbox-docker/docker-compose.override.yml"
        content: |
          version: '3.4'
          services:
            netbox:
              ports:
                - "8000:8080"
        mode: '0644'

    - name: Pull the latest NetBox Docker images
      ansible.builtin.shell:
        cmd: "docker-compose pull"
        chdir: "~/projects/netbox-docker"
      register: pull_output

    - name: Bring up the NetBox Docker containers in detached mode
      ansible.builtin.shell:
        cmd: "docker-compose up -d"
        chdir: "~/projects/netbox-docker"
      register: up_output

    - name: Create NetBox superuser
      ansible.builtin.shell:
        cmd: "docker-compose exec netbox /opt/netbox/netbox/manage.py createsuperuser"
        chdir: "~/projects/netbox-docker"
      async: 600
      poll: 0
      ignore_errors: true
