- name: Setup NetBox Docker
  hosts: all  # Adjust if you want to run on a remote server
  become: yes
  tasks:

    - name: Install required dependencies for Docker Compose
      ansible.builtin.package:
        name:
          - curl
          - python3-pip
          - libffi-dev
          - gcc
          - g++ 
          - docker.io
          - docker-compose
	        - git
        state: present

    - name: Clone NetBox Docker repository
      shell:
	      cmd: "git clone https://github.com/netbox-community/netbox-docker.git"

    - name: Add docker-compose override to expose port 8000
      ansible.builtin.copy:
        dest: "/home/test/netbox-docker/docker-compose.override.yml"
        content: |
          version: '3.4'
          services:
            netbox:
              ports:
                - "8000:8080"
        mode: '0644'

    - name: Add version to the top of docker-compose.yml
      lineinfile:
        path: docker-compose.yml
        line: "version: '3.4'"
        insertafter: BOF

- name: Read the file content
  command: cat docker-compose.yml
  register: file_content

- name: Process file content to skip first netbox:
  set_fact:
    processed_lines: |
      {{ file_content.stdout.split('\n') | map('trim') | list }}
    netbox_indices: "{{ processed_lines | select('search', '^netbox:') | list }}"
    skip_first_netbox: "{{ netbox_indices | split_at(1) }}"
  debug:
    skip_netbox: "{{ skip_first_netbox[0}}"
  Change_file_ignore:
      corrected:
      is_altered:

- name: Pull the latest NetBox Docker images
      shell:
        cmd: "docker-compose pull"
        chdir: "/home/test/netbox-docker"
      register: pull_output

    - name: Bring up the NetBox Docker containers in detached mode
      shell:
        cmd: "docker-compose up -d"
        chdir: "/home/test/netbox-docker"
      register: up_output

    - name: Create NetBox superuser
      shell:
        cmd: "docker-compose exec netbox /opt/netbox/netbox/manage.py createsuperuser"
        chdir: "/home/test/netbox-docker"
      async: 600
      poll: 0
      ignore_errors: true
