- name: Setup NetBox Docker
  hosts: all  # Adjust if you want to run on a remote server
  become: yes
  tasks:

    - name: Install required dependencies for Docker Compose
      ansible.builtin.package:
        name:
          - curl
          - python3-pip
          - libffi-dev
          - gcc
          - g++
          - docker.io
          - docker-compose
          - git
        state: present

    - name: Clone NetBox Docker repository
      shell:
        cmd: "git clone https://github.com/netbox-community/netbox-docker.git"

    - name: Add docker-compose override to expose port 8000
      ansible.builtin.copy:
        dest: "/home/test/netbox-docker/docker-compose.override.yml"
        content: |
          version: '3.4'
          services:
            netbox:
              ports:
                - "8000:8080"
        mode: '0644'

    - name: Add version to the top of docker-compose.yml
      ansible.builtin.lineinfile:
        path: "/home/test/netbox-docker/docker-compose.yml"
        line: "version: '3.4'"
        insertafter: BOF

    - name: Replace "netbox" with "- netbox" only after depends_on
      ansible.builtin.lineinfile:
        path: "/home/test/netbox-docker/docker-compose.yml"
        regexp: '^(\s*)depends_on:\s*$'
        insertafter: '^(\s*)depends_on:\s*$'
        line: '\1- netbox'
        backrefs: yes

    - name: Comment out "condition service_healthy" only within depends_on
      ansible.builtin.lineinfile:
        path: "/home/test/netbox-docker/docker-compose.yml"
        regexp: '^(\s*)condition: service_healthy\s*$'
        line: '\1#condition: service_healthy'
        backrefs: yes

    - name: Replace "netbox" with "- netbox" only after depends_on
      ansible.builtin.lineinfile:
        path: "/home/test/netbox-docker/docker-compose.yml"
        regexp: '^(\s*)depends_on:\s*$'
        insertafter: '^(\s*)depends_on:\s*$'
        line: '\1- netbox'
        backrefs: yes

    - name: Comment out "condition service_healthy" only within depends_on
      ansible.builtin.lineinfile:
        path: "/home/test/netbox-docker/docker-compose.yml"
        regexp: '^(\s*)condition: service_healthy\s*$'
        line: '\1#condition: service_healthy'
        backrefs: yes

    - name: cd
      shell:
        cmd: "cd /home/test/netbox-docker"

    - name: Pull the latest NetBox Docker images
      shell:
        cmd: "sudo docker-compose pull"

    - name: Bring up the NetBox Docker containers in detached mode
      shell:
        cmd: "sudo docker-compose up -d"

    - name: Create NetBox superuser
      shell:
        cmd: "sudo docker-compose exec netbox /opt/netbox/netbox/manage.py createsuperuser"
